---
title: "예외 처리"
excerpt: "JAVA의 예외 처리에 대해서 알아본다."
categories:
- CS
tags:
- JAVA
- 예외 처리
- CS
---

메소드가 해야 할 일을 수행할 수 없는 상황에 부딪힐 때 처리한다.

전통적인 방법은 메소드에서 오류코드를 반환하는 것이지만 예외처리 방식은 예외를 발생시키는 과정과 처리하는 과정을 분리할 수 있다. JAVA에서는 예외처리 방식을 사용하고 있다.



### 예외처리 계층도

![예외처리 계층](/assets/images/예외계층 구조.png)

모든 예외 클래스는 Throwable 클래스를 상속받고 있으며, Throwable은 최상위 클래스 Object의 자식 클래스이다.

Throwable을 상속받는 클래스는 Error와 Exception이 있다. Error는 시스템 레벨의 심각한 수준의 에러이기 때문에 시스템에 변화를 주어 문제를 처리해 하는 경우가 일반적이다. 반면에 Exception은 개발자가 로직을 추가하여 처리할 수 있다.

Exception은 수많은 자식클래스를 가지고 있다. 그 중 RuntimeException을 주목해야 한다.
RuntimeException은 CheckedException과 UncheckedException을 구분하는 기준이다.
Exception의 자식 클래스 중 RuntimeException을 제외한 모든 클래스는 CheckedException이며, RuntimeException과 그 자식 클래스들을 UncheckedException이라 부른다.



### CheckedException과 Unchecked(Runtime) Exception

| title          | Checked Exception                        | Unchecked Exception                      |
| -------------- | ---------------------------------------- | ---------------------------------------- |
| 처리여부           | 반드시 예외를 처리해야 한다.                         | 명시적인 처리를 강제하지 않는다.                       |
| 확인시점           | 컴파일 단계                                   | 런타임 단계                                   |
| 예외발생 시 트랜잭셕 처리 | roll-back 하지 않음                          | roll-back 함                              |
| 대표 예외          | Exception의 상속받는 하위 클래스 중 Runtime Exception을 제외한 모든 예외<br />- IOException<br />- SQLException | RuntimeException 하위 예외<br />- NullPointerException<br />- IllegalArgumentException<br />- IndexOutOfBoundException<br />- SystemException |



### 예외처리 방식

메소드 내부에서 예외가 발생할 때 처리할 수 있는 두 가지 방식을 설명해본다.

- 예외를 직접 처리하는 방식 (try ~ catch 사용)
  try를 사용하여 예외를 직접 잡는다.
  catch에서 예외의 종류를 명시하여 여러 가지 예외를 잡을 수 있다.

- 예외를 직접 처리하지 않고 호출한 쪽으로 넘기는 방식
  메소드 헤더에서 예외를 잡지 않고 던진다.
  throws 구문을 사용한다.



### 예외 던지기

예외를 직접 처리하지 않으려면 메소드 선언부에 throws 절을 사용한다.

```java
public void write(Object obj, String filename)
            throws IOException, RefelctiveOperationException {...}
```



### 예외 잡기

예외를 잡으려면 try 블럭을 이용한다.

```java
try {
  ...
} catch (예외클래스1 ex) {
  핸들러1
} catch (예외클래스2 ex) {
  핸들러2
} catch (예외클래스3 ex) {
  핸들러3
} finally {
  예외 발생 유무에 상관없이 마지막에 반드시 실행
}
```

try 블럭의 문장이 실행되다가 지정한 클래스의 예외가 발생하면 제어가 핸들러로 이동된다.
catch문 여러 개, finally 문은 하나만 정의가 가능하다. try문을 사용하기 위해서는 둘 중 하나가 필수적으로 정의되어 있어야 한다.
finally 구는 일반적으로 자원을 해제하기 위해 사용된다. ex) `fileWriter.close();`



### 여러 개의 예외를 같이 잡기

자바7 이후에서는 |(필터)을 사용할 수 있다.
```java
try {
  ...
} catch (ParseException | IOException e) {
  System.out.println("예외발생 : " + e.getMessage());
}
```

주의 ) 상속관계에 있는 예외는 같이 잡을 수 없다.



### try-with-resources 문
예외처리의 문제점은 리소스 관리이다.

- 자바7에서는 리소스를 확실하게 닫아주어야 한다.
  ```java
  try (FileInputStream in = new FileInputStream("text.txt")) {
    ...FileInputStream 으로부터 읽기 처리...
  }
  ```

- 자바9에서는 좀 더 나은 문법을 제공해준다.
  ```java
  FileInputStream in = new FileInputStream("text.txt");
  
  try (in) {
    ... FileInputStream 으로부터 읽기 처리 ...
  }
  ```

위 두 코드는 자원사용을 자동으로 종료해준다.



### 예외 다시 던지기, Exception re-throwing

예외를 다시 던지는 경우
- 예외 발생 시 당장 처리 방법을 모르는 경우
- 시스템 예외를 잡아서 사용자 정의 예외로 다시 던질 때
- Checked Exception을 잡아서 Unchecked Exception으로 다시 던질 때
  ```java
  try {
    ... 데이터베이스에 접근 ...
  } catch (SQLException se) {
    throw new MyException(se);
  }
  ```
